# Create a program that will play the “cows and bulls” game with the user.
# The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they
# have a “cow”. For every digit the user guessed correctly in the wrong place is
# a “bull.” Every time the user makes a guess, tell them how many “cows” and
# “bulls” they have. Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout teh game and tell
# the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could
# look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
#
# Until the user guesses the number.

import random

def calculate_cows_bulls(secret_num, user_guess):
    i = 0
    num_str = str(secret_num)
    cows_bulls = [0, 0] # [cows, bulls]
    while i < 4:
        if user_guess[i] in num_str:
            if user_guess[i] == num_str[i]:
                cows_bulls[1] += 1
            else:
                cows_bulls[0] += 1
        i += 1

    return cows_bulls


if __name__=='__main__':
    secret_num = random.randint(1000, 10000)
    # print(secret_num)
    print(f'Welcome to guessing game! Guess the secret number and win.')
    user_guess = input("Guess a number (or exit to end the game):  ")
    guess_count = 0
    while user_guess != 'exit':
        guess_count += 1
        if int(user_guess) < 1000 or int(user_guess) > 9999:
            print(f'Please enter a 4 digit number.')
        else:
            cows_bulls = calculate_cows_bulls(secret_num, user_guess)
            if cows_bulls[1] == 4:
                print(f'You guessed it!')
                break;
            else:
                print(f'{cows_bulls[0]} Cows, {cows_bulls[1]} Bulls')
        user_guess = input(f'Guess a number (or exit to end the game): ')

    print(f'You took {guess_count} guesses!')
